// GENERATED FILE - DO NOT EDIT
// This file is automatically generated from .env file

class EnvConfigGenerated {
  static final Map<String, String> values = {
    'API_URL': 'http://api:8000/api',
    'APP_ENV': 'production',
    'APP_DEBUG': 'false',
    'FLUTTER_BUILD_MODE': 'release',
  };
}